name: Build & Deploy

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: kalandozas/web:latest
                  build-args: |
                      NEXT_PUBLIC_GOOGLE_MAPSKEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPSKEY }}
                      NEXT_PUBLIC_EMAIL_USER=${{ secrets.NEXT_PUBLIC_EMAIL_USER }}
                      NEXT_PUBLIC_EMAIL_PASS=${{ secrets.NEXT_PUBLIC_EMAIL_PASS }}
                      NEXT_BASEURL=${{ secrets.NEXT_BASEURL }}
                      NEXT_FIREBASE_API_KEY=${{ secrets.NEXT_FIREBASE_API_KEY }}
                      NEXT_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_FIREBASE_AUTH_DOMAIN }}
                      NEXT_FIREBASE_PROJECTID=${{ secrets.NEXT_FIREBASE_PROJECTID }}
                      NEXT_FIREBASE_STORAGEBUCKET=${{ secrets.NEXT_FIREBASE_STORAGEBUCKET }}
                      NEXT_FIREBASE_MESSAGESENDERID=${{ secrets.NEXT_FIREBASE_MESSAGESENDERID }}
                      NEXT_FIREBASE_APPID=${{ secrets.NEXT_FIREBASE_APPID }}
                      NEXT_FIREBASE_MEASUREMENTID=${{ secrets.NEXT_FIREBASE_MEASUREMENTID }}
                      NEXT_PUBLIC_GOOGLE_GAID=${{ secrets.NEXT_PUBLIC_GOOGLE_GAID }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy app
              uses: appleboy/ssh-action@v0.1.2
              with:
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}
                  username: ${{secrets.SSH_USERNAME}}

                  script: |
                      cd /home/ubuntu
                      cd kalandozas
                      git pull
                      sudo docker --config ~/.kalandozas compose pull kalandozastravel
                      sudo docker --config ~/.kalandozas compose up -d
